### ISSUE TITLE
Change data props to accept array of image url  or array of image base64 

### ISSUE THREAD

**Issue by manneyugn** [imshines/react-lightbox-pack#2]
I think it would be more clear to change the data props to array of image than array of object with the image property

**Comment by imshines** [comment]
Hi 9tee, so you're saying instead of an object like this,
```[
{
    "id": 1,
    "image": "https://picsum.photos/200/800",
    "title": "Lorem Ipsum",
    "description":
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos assumenda, velit explicabo non at consequuntur accusamus hic optio alias error nisi sunt sint veniam aperiam similique dolor fugit itaque minima!"
  },
] 
```
You're telling to change it as an array like this?
```
[
"https://picsum.photos/200/800", "https://picsum.photos/200/800",
]
```

Is this right?

**Comment by imshines** [comment]
> I think it would be more clear to change the data props to array of image than array of object with the image property

I have added a new prop that will accept an array.
